# Generated by Django 3.1.2 on 2020-10-03 09:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20201003_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(default='lorem'),
            preserve_default=False,
        ),
    ]
