# Generated by Django 3.0.8 on 2020-10-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20201003_1441'),
        ('forum', '0002_auto_20201003_1606'),
    ]

    operations = [
    ]
