# Generated by Django 3.0.8 on 2020-07-31 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('challenge_finishers', models.ManyToManyField(blank=True, related_name='challenges_finished', to=settings.AUTH_USER_MODEL)),
                ('challenge_winners', models.ManyToManyField(blank=True, related_name='challenges_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('answer_type', models.CharField(choices=[('1', 'string'), ('2', 'textarea'), ('3', 'file')], max_length=10)),
                ('question_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_number', models.IntegerField()),
                ('answer_type', models.CharField(choices=[('1', 'string'), ('2', 'textarea'), ('3', 'file')], max_length=10)),
                ('answer_textarea', models.TextField(blank=True, null=True)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='answers')),
                ('answer_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.Challenge')),
                ('answer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
