# Generated by Django 3.0.8 on 2020-08-02 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='disqualified',
            field=models.ManyToManyField(blank=True, related_name='challenges_disqualified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_type',
            field=models.CharField(choices=[('1', 'textarea'), ('2', 'file')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('1', 'textarea'), ('2', 'file')], max_length=10),
        ),
    ]
