# Generated by Django 3.0.8 on 2020-08-02 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20200802_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='selected',
            field=models.ManyToManyField(blank=True, related_name='challenges_selected', to=settings.AUTH_USER_MODEL),
        ),
    ]
